services:
  - type: web
    name: f1gpt
    runtime: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ASTRA_DB_APPLICATION_TOKEN
        sync: false
      - key: ASTRA_DB_API_ENDPOINT
        sync: false
      - key: ASTRA_DB_NAMESPACE
        sync: false
      - key: ASTRA_DB_COLLECTION
        sync: false
